name: C/C++ CI

on:
  push:
    branches: [ "main","AldousBranch" ]
  pull_request:
    branches: [ "main","AldousBranch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3   
    - name: make test
      run: make test
    - name: run test
      run: ./test

